name: Self-Hosted Runner Test

on: [push]

jobs:
  test:
    runs-on: self-hosted
    container: ubuntu:20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        # Add your test commands here

